// eslint-disable-next-line
export default {
	cart: [],
	buyer: [],
	orders: [],
	products: [
		{
			id: 100,
			title: 'Bandeja con borde',
			price: 1200,
			description: 'Molde bandeja de 16 x 10 cm para resina',
			image: 'Images/ProductsImages/bandejaconborde.jpg',
		},
		{
			id: 101,
			title: 'Combo ceniceros',
			price: 6000,
			description: 'Moldes de silicona para resina: ceniceros x6 formas',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 102,
			title: 'Cenicero Corazon',
			price: 1100,
			description:
				'Molde de silicona para resina: cenicero con forma de corazon',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 103,
			title: 'cenicero cuadrado',
			price: 1200,
			description:
				'molde de silicona para resina: cenicero con forma de cuadrado',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 104,
			title: 'Cenicero redondo',
			price: 1200,
			description: 'Molde de silicona para resina: cenicero con forma redonda',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 105,
			title: 'Cenicero hexagono',
			price: 1200,
			description:
				'Molde de silicona para resina: cenicero con forma hexagonal',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 106,
			title: 'Cenicero triangulo',
			price: 1200,
			description:
				'Molde de silicona para resina: ceniceros con forma triangular',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 107,
			title: 'Cenicero hoja',
			price: 1200,
			description: 'Molde de silicona para resina: ceniceros con forma de hoja',
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 108,
			title: 'Circulo 29cm',
			price: 2000,
			description: 'Molde de silicona circulo de 29 cm',
			image: '/Images/ProductsImages/circulo29cm.jpg',
		},
		{
			id: 109,
			title: 'Dijes',
			price: 1400,
			description: 'Molde de silicona para resina para dijes en varias formas',
			image: '/Images/ProductsImages/dijes.jpg',
		},
		{
			id: 110,
			title: 'Escudos',
			price: 1500,
			description:
				'Molde de silicona para resina con forma de escudos 8 cavidades',
			image: '/Images/ProductsImages/escudos.jpg',
		},
		{
			id: 111,
			title: 'Expansores',
			price: 1600,
			description: 'Molde de silicona para resina forma de expansores',
			image: '/Images/ProductsImages/expansores.jpg',
		},
		{
			id: 112,
			title: 'Ninjacat x4',
			price: 1800,
			description: 'Molde de silicona con forma de gato ninjacat x4',
			image: '/Images/ProductsImages/gato4.jpg',
		},
		{
			id: 112,
			title: 'Ninjacat',
			price: 1100,
			description: 'Molde de silicona con forma de gato ninjacat',
			image: '/Images/ProductsImages/gatosimple.jpg',
		},
		{
			id: 113,
			title: 'Huesito x10',
			price: 2100,
			description: 'Molde de silicona con forma de huesito x10 cavidades',
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 114,
			title: 'Huesito',
			price: 1000,
			description: 'Molde de silicona con forma de huesito',
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 115,
			title: 'Huesito x3 cavidades',
			price: 1200,
			description: 'Molde de silicona forma de huesito x3 cavidades',
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 116,
			title: 'Llaveros circulos',
			price: 1500,
			description: 'Molde de silicona forma de llaveros circulares 5cm',
			image: '/Images/ProductsImages/llaveroscirculos.jpg',
		},
		{
			id: 117,
			title: 'Llaveros cuadrados',
			price: 1500,
			description: 'Molde de silicona forma de llaveros cuadrados 5cm',
			image: '/Images/ProductsImages/llaveroscuadrados.jpg',
		},
		{
			id: 118,
			title: 'Marcador 15x3',
			price: 1100,
			description: 'Molde de silicona forma de marcador 15x3cm',
			image: '/Images/ProductsImages/marcador15x3.jpg',
		},
		{
			id: 119,
			title: 'Marcador triple',
			price: 1700,
			description: 'Molde de silicona forma de marcador 15x3cm x 3 cavidades',
			image: '/Images/ProductsImages/marcadortriple.jpg',
		},
		{
			id: 120,
			title: 'Marcador 19x4',
			price: 1200,
			description: 'Molde de silicona forma de marcador 19x4cm',
			image: '/Images/ProductsImages/marcador15x3.jpg',
		},
		{
			id: 121,
			title: 'Paleta de maquillaje',
			price: 1000,
			description: 'Molde de silicona para paleta de maquillaje',
			image: '/Images/ProductsImages/paletamaquillaje.jpg',
		},
		{
			id: 122,
			title: 'Pastillas',
			price: 1000,
			description: 'Molde de silicona con forma de pastillas 1cm',
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 123,
			title: 'Pastillas',
			price: 1000,
			description: 'Molde de silicona con forma de pastillas 1cm',
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 124,
			title: 'Pastillas',
			price: 1000,
			description: 'Molde de silicona con forma de pastillas 1cm',
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 125,
			title: 'Puas',
			price: 1100,
			description: 'Molde de silicona con forma de puas de guitarra',
			image: '/Images/ProductsImages/puas.jpg',
		},
		{
			id: 126,
			title: 'Peine',
			price: 1100,
			description: 'Molde de silicona con forma de peine 15x6 cm',
			image: '/Images/ProductsImages/peine.jpg',
		},
		{
			id: 127,
			title: 'Picador',
			price: 1200,
			description: 'Molde de silicona con forma de picador con puntas',
			image: '/Images/ProductsImages/picador.jpg',
		},
		{
			id: 128,
			title: 'Picador 420',
			price: 1500,
			description: 'Molde de silicona con forma de picador',
			image: '/Images/ProductsImages/picador',
		},
		{
			id: 129,
			title: 'Combo posavasos con borde',
			price: 2700,
			description:
				'Combo x3 moldes de silicona con formas posavasos con borde.',
			image: '/Images/ProductsImages/posavasosconborde.jpg',
		},
		{
			id: 129,
			title: 'Posavaso hexagonal',
			price: 1000,
			description: 'Molde de silicona posavaso con borde forma hexagonal.',
			image: '/Images/ProductsImages/',
		},
		{
			id: 130,
			title: 'Posavaso cuadrado',
			price: 1000,
			description: 'Molde de silicona posavaso con borde forma cuadrado',
			image: '/Images/ProductsImages/',
		},
		{
			id: 131,
			title: 'Posavaso redondo',
			price: 1000,
			description: 'Molde de silicona posavaso con borde forma circular',
			image: '/Images/ProductsImages/',
		},
		{
			id: 132,
			title: 'Tapa de agenda A5',
			price: 1000,
			description:
				'Molde de silicona forma de tapa de agenda A5 con 6 agujeros',
			image: '/Images/ProductsImages/tapaagenda.jpg',
		},
		{
			id: 133,
			title: 'Tapa de agenda A5 doble',
			price: 2500,
			description:
				'Molde de silicona forma tapa de agenda A5 con 6 agujeros x2',
			image: '/Images/ProductsImages/',
		},
		{
			id: 134,
			title: 'Combo vela zig-zag',
			price: 2700,
			description: 'Moldes de silicona para velas forma zig zag curvo',
			image: '/Images/ProductsImages/',
		},
		{
			id: 135,
			title: 'Vela zig-zag curvo',
			price: 1500,
			description: 'Molde de silicona para velas forma zig-zag curvo',
			image: '/Images/ProductsImages/velazigzagcurva.jpg',
		},
		{
			id: 136,
			title: 'Vela zig-zag recta',
			price: 1500,
			description: 'Molde de silicona para velas forma zig-zag recta',
			image: '/Images/ProductsImages/velazigzagrecta.jpg',
		},
		{
			id: 300,
			title: 'Resina expoxi 300gr',
			price: 1900,
			description: 'Resina epoxi cristal tack 300gr',
			image: '/Images/ProductsImages/resinaepoxi300.jpg',
		},
		{
			id: 301,
			title: 'Resina epoxi 700gr',
			price: 3800,
			description: 'Resina epoxi cristal tack 700gr',
			image: '/Images/ProductsImages/resinaepoxi700.jpg',
		},
	],
};
