// eslint-disable-next-line
export default {
	cart: [],
	buyer: [],
	orders: [],
	products: [
		{
			id: 100,
			title: 'Bandeja con borde',
			type: 'MoldesResina',
			offer: true,
			price: 2600,
			description: 'Molde bandeja de 18x9cm para resina',
			sells: 0,
			image: '/Images/ProductsImages/bandejaconborde.jpg',
		},
		{
			id: 101,
			title: 'Combo ceniceros',
			type: 'MoldesResina',
			offer: false,
			price: 5780,
			description: `Moldes de silicona para resina ceniceros x6 formas 7cm:
						Cuadrado, Hoja, Corazón, Redondo, triangular, Hexágono`,
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 102,
			title: 'Cenicero Corazon',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'Molde de silicona para resina: cenicero con forma de corazon 8,5x8x1,5cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 103,
			title: 'cenicero cuadrado',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'molde de silicona para resina: cenicero con forma de cuadrado 8x8x1,8cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 104,
			title: 'Cenicero redondo',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'Molde de silicona para resina: cenicero con forma redonda 7x1,8cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 105,
			title: 'Cenicero hexagonal',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'Molde de silicona para resina: cenicero con forma hexagonal 8x7x1,5cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 106,
			title: 'Cenicero triangular',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'Molde de silicona para resina: ceniceros con forma triangular 8x1,7cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 107,
			title: 'Cenicero hoja',
			type: 'MoldesResina',
			offer: false,
			price: 1450,
			description:
				'Molde de silicona para resina: ceniceros con forma de hoja 8x8,5x1,5cm',
			sells: 0,
			image: '/Images/ProductsImages/ceniceros.jpg',
		},
		{
			id: 108,
			title: 'Circulo 29cm',
			type: 'MoldesResina',
			offer: false,
			price: 3851,
			description: 'Molde de silicona circulo de 29 cm',
			sells: 10,
			image: '/Images/ProductsImages/circulo29cm.jpg',
		},
		{
			id: 109,
			title: 'Dijes en formas varias',
			type: 'MoldesResina',
			offer: false,
			price: 2400,
			description:
				'Molde de silicona para resina para dijes en varias formas (11 cavidades)',
			sells: 15,
			image: '/Images/ProductsImages/dijes.jpg',
		},
		{
			id: 110,
			title: 'Escudos con agujero',
			type: 'MoldesResina',
			offer: false,
			price: 2250,
			description:
				'Molde de silicona para resina con forma de escudos 8 cavidades de 3,5cm',
			sells: 0,
			image: '/Images/ProductsImages/escudos.jpg',
		},
		{
			id: 111,
			title: 'Expansores en 9 medidas',
			type: 'MoldesResina',
			offer: false,
			price: 3370,
			description:
				'Molde de silicona para resina en forma de expansores con 18 cavidades en 9 medidas diferentes',
			sells: 0,
			image: '/Images/ProductsImages/expansores.jpg',
		},
		{
			id: 112,
			title: 'Ninjacat',
			type: 'MoldesResina',
			offer: true,
			price: 1350,
			description:
				'Molde de silicona para resina tipo llavero con forma de gato ninjacat defensa personal',
			sells: 0,
			image: '/Images/ProductsImages/gatosimple.jpg',
		},
		{
			id: 113,
			title: 'Huesito x10',
			type: 'MoldesResina',
			offer: false,
			price: 3755,
			description:
				'Molde de silicona tipo llavero con forma de huesito x10 cavidades de 7x4cm',
			sells: 0,
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 114,
			title: 'Huesito',
			type: 'MoldesResina',
			offer: true,
			price: 910,
			description: 'Molde de silicona tipo llavero con forma de huesito 7x4cm',
			sells: 0,
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 115,
			title: 'Huesito x3 cavidades',
			type: 'MoldesResina',
			offer: true,
			price: 1443,
			description:
				'Molde de silicona para resina, tipo llavero, forma de huesito x3 cavidades 5x3cm ',
			sells: 0,
			image: '/Images/ProductsImages/huesito10cavidades.jpg',
		},
		{
			id: 116,
			title: 'Llaveros circulos x8',
			type: 'MoldesResina',
			offer: false,
			price: 2500,
			description:
				'Molde de silicona para resina tipo llaveros con forma circular de 5cm con 8 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/llaveroscirculos.jpg',
		},
		{
			id: 117,
			title: 'Llaveros cuadrados 8 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 2505,
			description:
				'Molde de silicona para resina tipo llaveros cuadrados 5cm x 8 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/llaveroscuadrados.jpg',
		},
		{
			id: 118,
			title: 'Marcador 15x3',
			type: 'MoldesResina',
			offer: false,
			price: 1160,
			description: 'Molde de silicona forma de marcador 15x3cm',
			sells: 0,
			image: '/Images/ProductsImages/marcador15x3.jpg',
		},
		{
			id: 119,
			title: 'Marcador triple 15x3cm',
			type: 'MoldesResina',
			offer: false,
			price: 2410,
			description:
				'Molde de silicona para resina forma de marcador 15x3cm x 3 cavidades',
			sells: 5,
			image: '/Images/ProductsImages/marcadortriple.jpg',
		},
		{
			id: 120,
			title: 'Marcador 18x4',
			type: 'MoldesResina',
			offer: false,
			price: 1350,
			description: 'Molde de silicona forma de marcador 18x4cm',
			sells: 0,
			image: '/Images/ProductsImages/marcador15x3.jpg',
		},
		{
			id: 121,
			title: 'Paleta de maquillaje',
			type: 'MoldesResina',
			offer: false,
			price: 1925,
			description:
				'Molde de silicona para paleta de maquillaje pintura de uñas 12,5cm x 9,5cm',
			sells: 4,
			image:
				'https://drive.google.com/file/d/1PMt9raOjc4f6kLci623YzmqAqyMY5UE7/view?usp=sharing',
		},
		{
			id: 122,
			title: 'Pastillas x30 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 1440,
			description:
				'Molde de silicona para jabones con forma de pastillas 12x6mm',
			sells: 0,
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 123,
			title: 'Jabones 2x1cm 30 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 1620,
			description: 'Molde de silicona con forma de pastillas 1cm',
			sells: 0,
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 124,
			title: 'Pastillas x40 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 1160,
			description: 'Molde de silicona con forma de pastillas de 7x4mm',
			sells: 0,
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 125,
			title: 'Puas x10 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 1350,
			description:
				'Molde de silicona para resina con forma de puas de guitarra 10 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/puas.jpg',
		},
		{
			id: 127,
			title: 'Picador herb grinder',
			type: 'MoldesResina',
			offer: false,
			price: 1650,
			description:
				'Molde de silicona con forma de picador con puntas 5,5cm de diametro x 2,5cm de alto (estando cerrado)',
			sells: 0,
			image: '/Images/ProductsImages/picador.jpg',
		},
		{
			id: 128,
			title: 'Picador 420',
			type: 'MoldesResina',
			offer: false,
			price: 1850,
			description:
				'Molde de silicona con forma de picador sin puntas 6,5cm de diametro x 2,5cm de alto (estando cerrado)',
			sells: 0,
			image: '/Images/ProductsImages/picador',
		},
		{
			id: 129,
			title: 'Combo posavasos con borde',
			type: 'MoldesResina',
			offer: false,
			price: 3860,
			description:
				'Combo x3 moldes de silicona con formas posavasos con borde.',
			sells: 0,
			image: '/Images/ProductsImages/posavasosconborde.jpg',
		},
		{
			id: 130,
			title: 'Posavaso cuadrado',
			type: 'MoldesResina',
			offer: false,
			price: 1540,
			description: 'Molde de silicona posavaso con borde forma cuadrado',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 131,
			title: 'Posavasos redondo',
			type: 'MoldesResina',
			offer: false,
			price: 1540,
			description: 'Molde de silicona posavaso con borde forma circular',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 132,
			title: 'Tapa de agenda A5',
			type: 'MoldesResina',
			offer: false,
			price: 2795,
			description:
				'Molde de silicona forma de tapa de agenda A5 con 6 agujeros',
			sells: 0,
			image: '/Images/ProductsImages/tapaagenda.jpg',
		},
		{
			id: 133,
			title: 'Tapa de agenda A5 doble',
			type: 'MoldesResina',
			offer: true,
			price: 3851,
			description:
				'Molde de silicona forma tapa de agenda A5 con 6 agujeros x 2 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 134,
			title: 'Combo vela zig-zag',
			type: 'moldesvelas',
			offer: false,
			price: 3850,
			description: 'Moldes de silicona para velas forma zig zag curvo y recto',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 135,
			title: 'Vela zig-zag curvo',
			type: 'moldesvelas',
			offer: false,
			price: 2320,
			description: 'Molde de silicona para velas forma zig-zag curvo',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagcurva.jpg',
		},
		{
			id: 136,
			title: 'Vela zig-zag recta',
			type: 'moldesvelas',
			offer: false,
			price: 2320,
			description: 'Molde de silicona para velas forma zig-zag recta',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagrecta.jpg',
		},
		{
			id: 137,
			title: 'Posavasos hexagonal',
			type: 'MoldesResina',
			offer: false,
			price: 1540,
			description: 'Molde de silicona posavaso con borde forma hexagonal.',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 138,
			title: 'Ninjacat x4',
			type: 'MoldesResina',
			offer: false,
			price: 2880,
			description: 'Molde de silicona con forma de gato ninjacat x4',
			sells: 0,
			image: '/Images/ProductsImages/gato4.jpg',
		},
		{
			id: 139,
			title: 'Llaveros 3,5cm x12 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 2310,
			description: 'Molde de silicona tipo llavero. 12 cavidades 3,5cm',
			sells: 0,
			image: '',
		},
		{
			id: 140,
			title: 'Llaveros con forma de corazon 5cm x 8 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 2500,
			description:
				'Molde de silicona para resina tipo llavero de 8 cavidades con forma de corazón 5cm',
			sells: 0,
			image: '',
		},
		{
			id: 141,
			title: 'Posavasos circulares x6 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 2700,
			description:
				'Molde de silicona para resina tipo posavasos de 8cm x 6 cavidades de forma circular',
			sells: 0,
			image: '',
		},
		{
			id: 142,
			title: 'Posavasos x 3 formas',
			type: 'MoldesResina',
			offer: false,
			price: 2410,
			description:
				'Molde de silicona para resina tipo posavasos de 8cm x 3 cavidades (circular, cuadrada y hexagonal)',
			sells: 0,
			image: '',
		},
		{
			id: 143,
			title: 'Llaveros con forma de corazon 5cm x 3 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 1440,
			description:
				'Molde de silicona para resina tipo llavero de 3 cavidades con forma de corazón 5cm',
			sells: 0,
			image: '',
		},
		{
			id: 144,
			title: 'Bandeja de armado 20x12cm ',
			type: 'MoldesResina',
			offer: false,
			price: 3520,
			description:
				'Molde de silicona para resina con forma de bandeja de armado grow arte',
			sells: 0,
			image: '',
		},
		{
			id: 145,
			title: 'Posavasos cuadrado 4 cavidades',
			type: 'MoldesResina',
			offer: false,
			price: 2310,
			description:
				'Molde de silicona para resina con 4 cavidades cuadradas de 10cm',
			sells: 0,
			image: '',
		},
		{
			id: 146,
			title: 'Bandeja irregular 40x25cm',
			type: 'MoldesResina',
			offer: false,
			price: 5680,
			description:
				'Molde de silicona para resina con forma irregular para bandeja de 40x25cm acabado liso brillante',
			sells: 0,
			image: '',
		},
		{
			id: 147,
			title: 'Marcador doble 18x4cm',
			type: 'MoldesResina',
			offer: false,
			price: 1850,
			description:
				'Molde de silicona para resina forma de marcapaginas 18x4cm x 2 cavidades',
			sells: 0,
			image: '',
		},
		{
			id: 148,
			title: 'Paleta pintor 30cm',
			type: 'MoldesResina',
			offer: false,
			price: 2880,
			description:
				'Molde de silicona para paleta de pintor con agujero. 30x20cm acabado liso.',
			sells: 5,
			image: '',
		},
		{
			id: 149,
			title: 'Llaveros rectangulares',
			type: 'MoldesResina',
			offer: false,
			price: 1735,
			description:
				'Molde de silicona para resina tipo llaveros rectangulares 4,2x8cm 8 cavidades.',
			sells: 5,
			image: '',
		},
		{
			id: 150,
			title: 'Rectangulo 25x15cm',
			type: 'MoldesResina',
			offer: false,
			price: 2670,
			description:
				'Molde de silicona para rectangulo de 25x15x0,5 cm acabado liso.',
			sells: 0,
			image: '',
		},
		{
			id: 151,
			title: 'Arcoiris bandeja 23x23',
			type: 'MoldesResina',
			offer: false,
			price: 5780,
			description:
				'Molde de silicona tipo bandeja con forma de arcoiris de 23x23x2 cm',
			sells: 0,
			image: '',
		},
		{
			id: 152,
			title: 'Combo 4 moldes para llaveros',
			type: 'MoldesResina',
			offer: false,
			price: 8670,
			description:
				'Molde de silicona tipo llaveros de 8 cavidades de 5cm cada uno con formas cuadradas, circulares, hexagonales y corazones',
			sells: 0,
			image: '',
		},
		{
			id: 153,
			title: 'Soporte para celulares',
			type: 'MoldesResina',
			offer: false,
			price: 3465,
			description:
				'Molde de silicona para resina con forma de soporte de celulares acabado liso 20,5 x 9cm',
			sells: 0,
			image: '',
		},
		{
			id: 154,
			title: 'Vela con forma de almeja',
			type: 'moldesvelas',
			offer: false,
			price: 2600,
			description:
				'Moldes de silicona para velas con forma de almeja 9x6,5x4cm',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 155,
			title: 'Circulo 15cm',
			type: 'MoldesResina',
			offer: false,
			price: 1920,
			description:
				'Moldes de silicona para resina con forma de circulo acabado brillante 15x0,5cm',
			sells: 0,
			image: '/Images/ProductsImages/',
		},
		{
			id: 156,
			title: 'Arcoiris bandeja 20x10',
			type: 'MoldesResina',
			offer: false,
			price: 3470,
			description:
				'Molde de silicona tipo bandeja con forma de arcoiris de 20x10x2 cm',
			sells: 0,
			image: '',
		},
		{
			id: 157,
			title: 'Tabla picadas',
			type: 'MoldesResina',
			offer: false,
			price: 3850,
			description:
				'Molde de silicona para resina tipo paleta de pinturs/tabla de picadas 35x15x1cm',
			sells: 0,
			image: '',
		},
		{
			id: 158,
			title: 'Circulos varios tamaños 1, 2 y 3cm',
			type: 'MoldesResina',
			offer: false,
			price: 2250,
			description:
				'Molde de silicona para resina con 12 cavidades de 3cm, 12 de 2cm y 25 de 1cm. 0,5cm de espesor',
			sells: 0,
			image: '',
		},
		{
			id: 159,
			title: 'Llaveros hexagonales',
			type: 'MoldesResina',
			offer: false,
			price: 2505,
			description:
				'Molde de silicona para resina tipo llavero con 8 cavidades hexagonales de 5cm',
			sells: 0,
			image: '',
		},
		{
			id: 160,
			title: '4 cavidades para jabónes',
			type: 'MoldesResina',
			offer: false,
			price: 1820,
			description:
				'Molde de silicona para jabones/shampoo/cosmetica/velas con 4 cavidades cubicas de 4x4x4cm',
			sells: 0,
			image: '',
		},
		{
			id: 161,
			title: 'Cuadrado 20cm',
			type: 'MoldesResina',
			offer: false,
			price: 2700,
			description:
				'Molde de silicona para resina forma Cuadrada de 20x0,5 cm acabado liso.',
			sells: 0,
			image: '',
		},
		{
			id: 162,
			title: 'Rectangulo 17x8cm',
			type: 'MoldesResina',
			offer: false,
			price: 1445,
			description:
				'Molde de silicona para resina forma rectangular de 17x8cm acabado liso.',
			sells: 0,
			image: '',
		},
		{
			id: 163,
			title: '30 cavidades cuadradas',
			type: 'MoldesResina',
			offer: false,
			price: 1630,
			description:
				'Molde de silicona para resina 30 cavidades cuadradas 20x5 mm.',
			sells: 0,
			image: '',
		},
		{
			id: 164,
			title: 'Jabonera 10x9',
			type: 'MoldesResina',
			offer: false,
			price: 2220,
			description:
				'Molde de silicona para resina con forma de jabonera 10x9x1,5cm',
			sells: 0,
			image: '',
		},
		{
			id: 166,
			title: 'Bandeja 20x12 para sushi',
			type: 'MoldesResina',
			offer: false,
			price: 2700,
			description:
				'Molde de silicona para resina con forma de bandeja con borde irregular para sushi 20x12cm',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagrecta.jpg',
		},
		{
			id: 167,
			title: 'Posavasos con forma irregular',
			type: 'MoldesResina',
			offer: false,
			price: 1155,
			description:
				'Molde de silicona para resina con forma de posavasos bordes irregulares 9cm',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagrecta.jpg',
		},
		{
			id: 168,
			title: '8 cavidades para jabónes/velas',
			type: 'moldesvelas',
			offer: false,
			price: 1700,
			description: `Molde de silicona para con 8 cavidades cubicas de 4cm`,
			sells: 0,
			image: '',
		},
		{
			id: 169,
			title: '4 cavidades para jabónes masajeadores',
			type: 'moldesvelas',
			offer: false,
			price: 2600,
			description:
				'Molde de silicona para jabones con 4 cavidades con forma de jabon masajeador 100gr',
			sells: 0,
			image: '',
		},
		{
			id: 170,
			title: '4 cavidades para jabónes/shampo/velas 8x6x2cm',
			type: 'moldesvelas',
			offer: false,
			price: 3420,
			description:
				'Molde de silicona para jabónes/shampo/velas con 4 cavidades con forma rectangular 8x6x2cm',
			sells: 0,
			image: '',
		},
		{
			id: 171,
			title: '4 cavidades para jabónes/shampo/velas 6x4x3cm',
			type: 'moldesvelas',
			offer: false,
			price: 1735,
			description:
				'Molde de silicona para jabónes/shampo/velas con 4 cavidades con forma rectangular 6x4x3cm',
			sells: 0,
			image: '',
		},
		{
			id: 172,
			title: '8 cavidades cilindricas para velas',
			type: 'moldesvelas',
			offer: false,
			price: 3275,
			description:
				'Molde de silicona para jabónes/shampo/velas con 8 cavidades con forma cilindrica 4x4cm',
			sells: 0,
			image: '',
		},
		{
			id: 173,
			title: 'Circulo 20cm',
			type: 'MoldesResina',
			offer: false,
			price: 2890,
			description:
				'Molde de silicona para resina circulo de 20 cm acabado brillante',
			sells: 10,
			image: '/Images/ProductsImages/circulo29cm.jpg',
		},
		{
			id: 174,
			title: 'Escudos sin agujeros',
			type: 'MoldesResina',
			offer: false,
			price: 1780,
			description:
				'Molde de silicona para resina con forma de escudos sin agujeros 8 cavidades de 3,5cm',
			sells: 0,
			image: '/Images/ProductsImages/escudos.jpg',
		},
		{
			id: 175,
			title: 'Pastillas x30 cavidades 20mm',
			type: 'MoldesResina',
			offer: false,
			price: 1640,
			description: 'Molde de silicona para jabones con forma de pastillas 20mm',
			sells: 0,
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 176,
			title: 'Posavasos triangular',
			type: 'MoldesResina',
			offer: false,
			price: 2215,
			description:
				'Molde de silicona para resina con forma de triangulos con un borde irregular para posavasos 4 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/pastillas.jpg',
		},
		{
			id: 177,
			title: 'Bandeja irregular 29x17cm',
			type: 'MoldesResina',
			offer: false,
			price: 3180,
			description:
				'Molde de silicona para resina con forma irregular para bandeja de 29x17cm acabado liso brillante',
			sells: 0,
			image: '',
		},
		{
			id: 178,
			title: 'Paleta pintor 8,5cm',
			type: 'MoldesResina',
			offer: false,
			price: 1445,
			description:
				'Molde de silicona para paleta de pintor con agujero. 8,5cm acabado liso.',
			sells: 0,
			image: '',
		},
		{
			id: 179,
			title: 'Tapa agenda A6 doble',
			type: 'MoldesResina',
			offer: false,
			price: 3370,
			description: 'Molde de silicona para tapa agenda tamaño A6 para anillado',
			sells: 100,
			image: '',
		},
		{
			id: 180,
			title: 'Arcoiris 7x7',
			type: 'MoldesResina',
			offer: false,
			price: 2310,
			description: 'Molde de silicona con forma de arcoiris de 7x7x2 cm',
			sells: 0,
			image: '',
		},
		{
			id: 182,
			title: 'LLavero camiseta x3 cav.',
			type: 'MoldesResina',
			offer: true,
			price: 1440,
			description:
				'Molde de silicona con 3 cavidades tipo llavero con forma de camiseta de futlbol x3 cavidades 5x3,6cm',
			sells: 0,
			image: '',
		},
		{
			id: 183,
			title: 'LLavero circulos x3 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 1440,
			description:
				'Molde de silicona con 3 cavidades tipo llavero con forma de circular 3 cavidades 5cm',
			sells: 0,
			image: '',
		},
		{
			id: 184,
			title: 'Abecedario y numeros',
			type: 'MoldesResina',
			offer: false,
			price: 3275,
			description:
				'Molde de silicona abcedario y numeros de 3cm y 0,7cm de profundidad',
			sells: 0,
			image: '',
		},
		{
			id: 185,
			title: 'LLavero gatito x3 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 1440,
			description:
				'Molde de silicona con 3 cavidades tipo llavero con forma de gatito 3 cavidades 3x3cm',
			sells: 0,
			image: '',
		},
		{
			id: 186,
			title: 'LLavero huesito x8 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 2890,
			description:
				'Molde de silicona con 8 cavidades tipo llavero con forma de huesito x8 cavidades 5x3cm',
			sells: 0,
			image: '',
		},
		{
			id: 187,
			title: 'Cilindro 4cm',
			type: 'moldesvelas',
			offer: false,
			price: 1170,
			description: 'Molde de silicona con forma de cilindro de 4cm',
			sells: 0,
			image: '',
		},
		{
			id: 188,
			title: 'LLavero gatito x8 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 2600,
			description:
				'Molde de silicona con 8 cavidades tipo llavero con forma de gatito 8 cavidades 3x3cm',
			sells: 0,
			image: '',
		},
		{
			id: 189,
			title: 'Llaveros cuadrados x3 cav.',
			type: 'MoldesResina',
			offer: false,
			price: 1440,
			description:
				'Molde de silicona para resina tipo llaveros cuadrados 5cm x 3 cavidades',
			sells: 0,
			image: '/Images/ProductsImages/llaveroscuadrados.jpg',
		},
		{
			id: 190,
			title: 'LLavero camiseta x11 cav.',
			type: 'MoldesResina',
			offer: true,
			price: 3270,
			description:
				'Molde de silicona con 11 cavidades tipo llavero con forma de camiseta de futlbol x3 cavidades 5x3,6cm',
			sells: 0,
			image: '',
		},
		{
			id: 191,
			title: 'Posavasos forma corazon x2 cav.',
			type: 'MoldesResina',
			offer: true,
			price: 1820,
			description:
				'Molde de silicona con dos cavidades con forma de corazon 9x8cm acabado liso',
			sells: 0,
			image: '',
		},
		{
			id: 192,
			title: 'Molde silicona 30 cav cuadradas',
			type: 'MoldesResina',
			offer: true,
			price: 1630,
			description:
				'Molde de silicona con 30 cavidades con forma de cuadrada 20x5mm acabado liso',
			sells: 0,
			image: '',
		},
		{
			id: 193,
			title: 'Jabonera 8x8cm Bubble',
			type: 'MoldesResina',
			offer: false,
			price: 2220,
			description: 'Molde de silicona para resina con forma de jabonera 8x8cm',
			sells: 0,
			image: '',
		},
		{
			id: 194,
			title: 'Bandeja 35x10 para sushi',
			type: 'MoldesResina',
			offer: false,
			price: 3370,
			description:
				'Molde de silicona para resina con forma de bandeja con borde irregular para sushi 35x10cm acabado liso',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagrecta.jpg',
		},
		{
			id: 195,
			title: 'Vela forma simetrica',
			type: 'moldesvelas',
			offer: false,
			price: 2310,
			description:
				'Molde de silicona para velas forma simetrica 20cm clande soja',
			sells: 0,
			image: '/Images/ProductsImages/velazigzagcurva.jpg',
		},
		{
			id: 196,
			title: 'Tapa agenda A4 para anillado',
			type: 'MoldesResina',
			offer: false,
			price: 3060,
			description: 'Molde de silicona para tapa agenda tamaño A4 para anillado',
			sells: 100,
			image: '',
		},
		{
			id: 197,
			title: 'Tapa agenda A5 para anillado',
			type: 'MoldesResina',
			offer: false,
			price: 2610,
			description: 'Molde de silicona para tapa agenda tamaño A5 para anillado',
			sells: 100,
			image: '',
		},
		{
			id: 198,
			title: 'Tapa agenda A4 Doble para anillado ',
			type: 'MoldesResina',
			offer: false,
			price: 5400,
			description: 'Molde de silicona para tapa agenda tamaño A4 para anillado',
			sells: 100,
			image: '',
		},
		{
			id: 199,
			title: 'Llavero copa del mundo x3 cav',
			type: 'MoldesResina',
			offer: false,
			price: 1530,
			description:
				'Molde de silicona para llaveros con forma de la copa del mundo 3 cavidades',
			sells: 100,
			image: '',
		},
		{
			id: 200,
			title: 'Llavero copa del mundo x8 cav',
			type: 'MoldesResina',
			offer: false,
			price: 2520,
			description:
				'Molde de silicona para llaveros con forma de la copa del mundo 8 cavidades',
			sells: 100,
			image: '',
		},
		{
			id: 201,
			title: 'Posavasos doble panal 9cm',
			type: 'MoldesResina',
			offer: false,
			price: 2520,
			description:
				'Molde de silicona para posavasos con dos cavidades forma de panal',
			sells: 100,
			image: '',
		},
		{
			id: 202,
			title: 'Circulo 35cm',
			type: 'MoldesResina',
			offer: false,
			price: 3851,
			description:
				'Molde de silicona circulo de 35x3cm. Apto para resina,cemento, yeso, etc.',
			sells: 0,
			image: '/Images/ProductsImages/circulo29cm.jpg',
		},
		{
			id: 203,
			title: 'Circulo 50cm',
			type: 'MoldesResina',
			offer: false,
			price: 3851,
			description:
				'Molde de silicona circulo de 50x3cm. Apto para resina,cemento, yeso, etc.',
			sells: 0,
			image: '/Images/ProductsImages/circulo29cm.jpg',
		},

		{
			id: 300,
			title: 'Resina expoxi 300gr',
			type: 'ProductosVarios',
			offer: true,
			price: 3180,
			description: 'Resina epoxi marca cristal tack 300gr',
			sells: 20,
			image: '/Images/ProductsImages/resinaepoxi300.jpg',
		},
		{
			id: 301,
			title: 'Resina epoxi 700gr',
			type: 'ProductosVarios',
			offer: false,
			price: 6100,
			description: 'Resina epoxi marca cristal tack 700gr',
			sells: 0,
			image: '/Images/ProductsImages/resinaepoxi700.jpg',
		},
		{
			id: 304,
			title: 'Pasta colorante rosa para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento rosa 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 305,
			title: 'Pasta colorante amarillo para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento amarillo 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 306,
			title: 'Pasta colorante azul para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 810,
			description: 'Pasta colorante para resinas pigmento azul 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 307,
			title: 'Resina al agua Ecocryil 1,4kg',
			type: 'ProductosVarios',
			offer: false,
			price: 2650,
			description: 'Resina epoxi marca ecocryil de 1,4kg simil ceramigca',
			sells: 0,
			image: '/Images/ProductsImages/resinaepoxi700.jpg',
		},
		{
			id: 308,
			title: 'Pasta colorante negro para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento negro 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 309,
			title: 'Pasta colorante fucsia para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento fucsia 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 310,
			title: 'Pasta colorante rojo para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 810,
			description: 'Pasta colorante para resinas pigmento rojo 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 311,
			title: 'Resina al agua Ecocryil 700g',
			type: 'ProductosVarios',
			offer: false,
			price: 1900,
			description: 'Resina epoxi marca ecocryil de 700g simil ceramigca',
			sells: 0,
			image: '/Images/ProductsImages/resinaepoxi700.jpg',
		},
		{
			id: 312,
			title: 'Pasta colorante blanco para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento blanco 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 313,
			title: 'Limpiador DPM liquido',
			type: 'ProductosVarios',
			offer: false,
			price: 1170,
			description: 'Limpiador liquido sin solventes para resinas epoxi 250cc',
			sells: 0,
			image: '',
		},
		{
			id: 314,
			title: 'Resina epoxi dicast 41',
			type: 'ProductosVarios',
			offer: false,
			price: 1170,
			description: 'Resina epoxi dicast 41 plastificada color natural 540g',
			sells: 0,
			image: '',
		},
		{
			id: 315,
			title: 'Resina epoxi glosstack 210gr',
			type: 'ProductosVarios',
			offer: false,
			price: 2430,
			description:
				'Resina epoxi glosstack cristal 210gr, dimensional epoxi cristalino, para acabados.',
			sells: 0,
			image: '',
		},
		{
			id: 316,
			title: 'Pasta colorante verde para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 675,
			description: 'Pasta colorante para resinas pigmento verde 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 317,
			title: 'Pasta colorante violeta para resinas',
			type: 'ProductosVarios',
			offer: false,
			price: 810,
			description: 'Pasta colorante para resinas pigmento violeta 25gr',
			sells: 0,
			image: '',
		},
		{
			id: 318,
			title: 'Resina epoxi glosstack 210gr',
			type: 'ProductosVarios',
			offer: false,
			price: 2430,
			description:
				'Resina epoxi glosstack cristal 210gr, dimensional epoxi cristalino, para acabados.',
			sells: 0,
			image: '',
		},
		{
			id: 319,
			title: 'Resina poliuretano Ebalta sg2000 400g',
			type: 'ProductosVarios',
			offer: false,
			price: 4320,
			description:
				'Compuesto de colada base poliuretano de muy baja viscosidad y endurecimiento rápido y alta calidad de reproducción de detalles. Color blanco tiza.',
			sells: 0,
			image: '',
		},
		{
			id: 320,
			title: 'Caucho RTV silcast 7020 500g',
			type: 'ProductosVarios',
			offer: false,
			price: 5760,
			description: 'Caucho de siliconas rtv silcast 7020 x500gr',
			sells: 0,
			image: '',
		},

		{
			id: 400,
			title: 'Tapas optica Chevrolet Cruze LTZ',
			type: '3d',
			offer: false,
			price: 2250,
			description: 'tapas optica para chevrolet Cruze LTZ extendida para led',
			sells: 0,
			image: '',
		},
		{
			id: 401,
			title: 'Tapas optica Peugeot 208',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Juego de tapas para peugeot 208, flexibles goma, fabricadas con impresión 3D',
			sells: 0,
			image: '',
		},
		{
			id: 402,
			title: 'Tapas optica Chevrolet Cruze LT',
			type: '3d',
			offer: false,
			price: 2550,
			description:
				'tapas optica para chevrolet Cruze LT extendida para led Aptas para colocarle el oring original de las tapas (no incluyen oring) Consultar por tapas H15 o H7',
			sells: 0,
			image: '',
		},
		{
			id: 403,
			title: 'Tapas optica Chevrolet Cruze LT H7',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'tapas optica para chevrolet Cruze LT H7 extendida para led Aptas para colocarle el oring original de las tapas (no incluyen oring)',
			sells: 0,
			image: '',
		},
		{
			id: 404,
			title: 'Tapas optica Chevrolet Cruze LT Guantera',
			type: '3d',
			offer: false,
			price: 3700,
			description:
				'tapas optica para chevrolet Cruze Incluye las 4 tapas (H15 y H7) extendida para led Aptas para colocarle el oring original de las tapas (no incluyen oring)',
			sells: 0,
			image: '',
		},
		{
			id: 405,
			title: 'Tapas optica BMW Gs F800 (17/18)',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica para BMW Gs F800 modelo (2017/2018) extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 406,
			title: 'Tapas optica BMW Gs F800 (16/17)',
			type: '3d',
			offer: false,
			price: 1350,
			description:
				'Par de tapas optica para BMW Gs F800 modelo (2016/2017) extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 407,
			title: 'Tapas optica Yamaha super Tenere',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica extendidas para led para Yamaha super Tenere extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 408,
			title: 'Tapas optica BMW Gs F800',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica para BMW Gs F800 y similares con tapas ovaladas extendidas para colocar led, ver foto de tapas originales, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 409,
			title: 'Tapas optica BMW s1000rr Xr y otros',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica para BMW s1000rr Xr y otros extendidas para colocar led, ver foto de tapas originales, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 410,
			title: 'Velador con forma de luna 14cm + base',
			type: '3d',
			offer: false,
			price: 2520,
			description:
				'Lampara luna velador 14cm con base decoración. Fabricada mediante impresión 3D',
			sells: 0,
			image: '',
		},
		{
			id: 411,
			title: 'Tapas optica BMW Gs 1200',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica para BMW Gs 1200 extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 412,
			title: 'Soporte stand notebook',
			type: '3d',
			offer: false,
			price: 1500,
			description:
				'Soporte para notebook, refrigeracio, 5 posiciones, portatil con antideslizante',
			sells: 5,
			image: '',
		},
		{
			id: 413,
			title: 'Tapas optica Peugeot 207',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica para Peugeot 207 extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 414,
			title: '10 llaveros ninjacat',
			type: '3d',
			offer: false,
			price: 1530,
			description:
				'10 llaveros defensa personal ninjacat colores varios, impresion 3D',
			sells: 0,
			image: '',
		},
		{
			id: 415,
			title: 'Tapas optica Hyundai tucson',
			type: '3d',
			offer: false,
			price: 2000,
			description:
				'Par de tapas optica para Hyundai tucson extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 416,
			title: 'Control de velocidad crucero para motos',
			type: '3d',
			offer: false,
			price: 600,
			description:
				' Control de velocidad crucero para todo tipo de moto, y cualquier medida de puño. UNIVERSAL - Adaptable a cualquier marca y modelo de moto.',
			sells: 0,
			image: '',
		},
		{
			id: 417,
			title: 'Tapas optica Yamaha R3',
			type: '3d',
			offer: false,
			price: 2100,
			description:
				'Par de tapas optica para Yamaha R3 extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 418,
			title: 'Velador con forma de luna 18cm + base',
			type: '3d',
			offer: false,
			price: 2890,
			description:
				'Lampara luna velador 18cm con base decoración. Fabricada mediante impresión 3D',
			sells: 0,
			image: '',
		},
		{
			id: 419,
			title: 'Tapas optica Chevrolet Tracker led 17/18',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Par de tapas optica Chevrolet Tracker led 17/18 extendidas para colocar led, colocar el oring de las tapas originales',
			sells: 0,
			image: '',
		},
		{
			id: 420,
			title: '50 llaveros ninjacat',
			type: '3d',
			offer: false,
			price: 4500,
			description:
				'50 llaveros defensa personal ninjacat colores varios, impresion 3D',
			sells: 0,
			image: '',
		},
		{
			id: 421,
			title: 'Soporte playstation 4',
			type: '3d',
			offer: false,
			price: 630,
			description:
				'soporte para playstation 4 para refrigeracion, mejor circulacion de aire',
			sells: 0,
			image: '',
		},
		{
			id: 422,
			title: 'Tapas optica Chevrolet Cruze LT H15',
			type: '3d',
			offer: false,
			price: 1710,
			description:
				'tapas optica para chevrolet Cruze LT H15 ALTAS extendida para led Aptas para colocarle el oring original de las tapas.',
			sells: 0,
			image: '',
		},
		{
			id: 423,
			title: 'Tapas optica Chevrolet Onix',
			type: '3d',
			offer: false,
			price: 2250,
			description:
				'Juego de tapas optica para chevrolet Onix extendida para led',
			sells: 0,
			image: '',
		},
		{
			id: 424,
			title: 'Exhibidor de lentes',
			type: '3d',
			offer: false,
			price: 2700,
			description: 'Exhibidor de lentes para optica de impresion 3D',
			sells: 0,
			image: '',
		},
	],
};
